name: Submit parking form

on:
  schedule:
    - cron: '0 4 * * *'  # Adjust to your local time if needed
  workflow_dispatch:

jobs:
  submit-form:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Chrome and Chromedriver (Ubuntu package versions)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable chromium-chromedriver

      - name: Install Python dependencies
        run: pip install selenium

      - name: Run form submit script
        run: python form_submit.py

      - name: List files (debug)
        run: ls -alh

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: confirmation
          path: confirmation.png
