name: Daily Car Register

on:
  schedule:
     - cron: '24 3 * * *'  # 10:18 PM CDT
     - cron: '26 3 * * *' # Runs daily at 1:30 PM UTC (8:30 AM CDT)
  workflow_dispatch:        # Optional: allow manual trigger

jobs:
  submit-form:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Log current UTC time
        run: date -u    

      - name: Install dependencies
        run: pip install requests

      - name: Submit parking form
        run: python form_submit.py
