name: Daily Form Submission

on:
  schedule:
    - cron: '0 5 * * *' # Runs every day at 05:00 UTC
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  submit-form:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Clones your repository to the runner

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Download Chrome Browser for Testing
      run: |
        curl -L -o chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.92/linux64/chrome-linux64.zip

    - name: Extract Chrome Browser and Chromedriver
      run: |
        unzip -o chrome-linux64.zip -d .
        unzip -o chromedriver-linux64.zip -d .

    - name: Make Chrome and Chromedriver Executable
      run: |
        chmod +x ./chrome-linux64/chrome
        chmod +x ./chromedriver-linux64/chromedriver

    # --- DEBUG STEPS TO DIAGNOSE CHROME VERSION ---
    - name: Debug: Verify Chrome Binary Permissions and Path
      run: ls -la ./chrome-linux64/chrome

    - name: Debug: Get Version of Extracted Chrome Binary
      run: ./chrome-linux64/chrome --version
    # --- END DEBUG STEPS ---

    - name: Run form submit script
      run: python form_submit.py

    - name: Upload confirmation screenshot
      uses: actions/upload-artifact@v4
      with:
        name: confirmation-screenshot
        path: |
          confirmation.png
          error_screenshot.png
        if-no-files-found: ignore
