name: submit-form

on:
  schedule:
    - cron: '0 4 * * *'  # 11 PM CST
  workflow_dispatch:

jobs:
  submit-form:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome and Chromedriver (v124 manual method)
        run: |
          # Install Chrome
          wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux/x64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

          # Install Chromedriver
          wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux/x64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install Selenium
        run: pip install selenium

      - name: Run form submit script
        run: python submit.py

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: confirmation
          path: confirmation.png
