name: Daily Form Submission

on:
  schedule:
    - cron: '0 5 * * *' # Runs every day at 05:00 UTC
  workflow_dispatch # Allows manual triggering from the GitHub UI

jobs:
  submit-form:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Clones your repository to the runner

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        # No need to install Chrome via apt-get if we use Chrome for Testing binary

    - name: Extract Chrome Browser and Chromedriver
      run: |
        unzip -o chrome-linux64.zip -d . # Extract Chrome to current dir
        unzip -o chromedriver-linux64.zip -d . # Extract Chromedriver to current dir

    - name: Make Chrome and Chromedriver Executable
      run: |
        chmod +x ./chrome-linux64/chrome
        chmod +x ./chromedriver-linux64/chromedriver

    - name: Run form submit script
      run: python form_submit.py

    - name: Upload confirmation screenshot
      uses: actions/upload-artifact@v4
      with:
        name: confirmation-screenshot
        path: |
          confirmation.png
          error_screenshot.png # Also upload error screenshot if it exists
        if-no-files-found: ignore # Don't fail if screenshot isn't there
