name: Submit parking form

on:
  schedule:
    - cron: '0 4 * * *' # Runs every day at 4 AM UTC (adjust if needed for your timezone)
  workflow_dispatch: # This enables manual triggering from GitHub Actions UI

jobs:
  submit-form:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Chrome + Chromedriver (v124)
        run: |
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/124.0.6367.91/linux64/chrome-linux64.zip
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/124.0.6367.91/linux64/chromedriver-linux64.zip
          unzip chrome-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          echo 'export PATH=/opt/chrome:$PATH' >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install selenium

      - name: Debug - Print GITHUB_WORKSPACE and list files
        run: |
          echo "GITHUB_WORKSPACE is: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE
          ls -la . # Also list files in current working directory

      - name: Run form submit script
        run: python form_submit.py

      - name: Debug - List files after script run
        run: |
          echo "Files after script run:"
          ls -la $GITHUB_WORKSPACE
          ls -la .

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: confirmation
          path: confirmation.png
