name: submit-form

on:
  schedule:
    - cron: '0 4 * * *'  # 4 AM UTC = 11 PM CDT
  workflow_dispatch:

jobs:
  submit-form:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install specific Chrome version (v124)
        run: |
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.91-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_124.0.6367.91-1_amd64.deb

      - name: Install matching ChromeDriver (v124)
        run: |
          wget https://chromedriver.storage.googleapis.com/124.0.6367.91/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install Selenium
        run: pip install selenium

      - name: Run form submit script
        run: python submit.py

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: confirmation
          path: confirmation.png
